/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/admin/ablations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** The same day scheduled four ways — FIFO, RR, DRR (+ aging, + cohesion), SJF (§6.3, §10.5) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        seed?: number;
                        seeds?: number;
                        stations?: number;
                        demand_multiplier?: number;
                        quantum?: number;
                    };
                };
            };
            responses: {
                /** @description six arms, in §6.3 order */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Ablation"];
                    };
                };
                /** @description no admin session — four runs per seed */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Who is signed in — the dashboard's first paint */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description the signed-in admin */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminUser"];
                    };
                };
                /** @description no session */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /** Signs in (§13.4) — identical response for a wrong password or an unknown email */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        email: string;
                        password: string;
                    };
                };
            };
            responses: {
                /** @description signed in */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminUser"];
                    };
                };
                /** @description wrong email or password */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        /** Signs out */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description signed out */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/scheduler_config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The store's effective scheduler config (§6.6, §10.6) — every key present, defaults included */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description effective config */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SchedulerConfigResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Applies a scheduler config change and returns what is now live (§10.6) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** @description A subset of UpdateSchedulerConfig::SCHEMA keys — merged, not replaced */
                        scheduler_config: Record<string, never>;
                    };
                };
            };
            responses: {
                /** @description now live */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SchedulerConfigResponse"];
                    };
                };
                /** @description an invalid or unknown key */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/api/v1/admin/prep_time_stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The learned prep time (§7.3) beside the seeded guess, per menu item */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description prep time stats */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PrepTimeStats"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/board": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The customer board: making + ready, first names and codes only (§9.5, §13.1) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description board snapshot */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BoardUpdate"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/breaking_points": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Raises demand until overall p90 crosses target — the shop's real capacity (§10.5 #4) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        seed?: number;
                        seeds?: number;
                        stations?: number;
                        target_seconds?: number;
                    };
                };
            };
            responses: {
                /** @description the swept points, ascending, and the capacity they found */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BreakingPoint"];
                    };
                };
                /** @description no admin session */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/kds/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Exchanges a barista PIN and station for a station token (§13.3) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        barista_pin: string;
                        station_id: number;
                    };
                };
            };
            responses: {
                /** @description session issued */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["KdsSession"];
                    };
                };
                /** @description wrong PIN or unknown station — identical either way, so the response cannot enumerate stations */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/kds/queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The scheduler-ordered queue: in-progress work, next-up, and depth (§9.4) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description queue snapshot */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["QueueUpdate"];
                    };
                };
                /** @description no station token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/kds/items/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Claims the oldest queued drink — no id, the server decides (§6.2) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description claimed drink */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["KdsItem"];
                    };
                };
                /** @description nothing queued */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/kds/items/{id}/finish": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Finishes a drink */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description finished drink */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["KdsItem"];
                    };
                };
                /** @description the drink was never started */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/kds/items/{id}/fail": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Fails a drink for a reason and returns the remake (§9.4) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        reason: components["schemas"]["FailReason"];
                    };
                };
            };
            responses: {
                /** @description the remake, not the failed drink */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["KdsItem"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/kds/items/{id}/undo": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reverts the last transition within the 60s window (§9.4) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description reverted drink */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["KdsItem"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/menu": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Returns the available menu */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description menu */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Menu"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Kiosk connectivity probe (§9.3) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description store health */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Health"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Places an order (§9.1) — payment is authorized in the same transaction (§9.3) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        order: {
                            /** @enum {string} */
                            source: "kiosk" | "web";
                            customer_first_name?: string;
                            customer_phone?: string;
                            items: {
                                menu_item_id: number;
                                option_ids?: number[];
                            }[];
                        };
                    };
                };
            };
            responses: {
                /** @description order placed */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PlacedOrder"];
                    };
                };
                /** @description no items */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/{pickup_code}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The 4-character unambiguous pickup code (§13.1) — the capability token, not an id */
                pickup_code: string;
            };
            cookie?: never;
        };
        /** Order status and ETA (§9.1) — public, the code is the token */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The 4-character unambiguous pickup code (§13.1) — the capability token, not an id */
                    pickup_code: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description order status */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PlacedOrder"];
                    };
                };
                /** @description unknown code */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/quantum_sweeps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** The same day run at ten quantum values, so the crossover can be read off the chart (§10.5 #2) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        seed?: number;
                        seeds?: number;
                        stations?: number;
                        demand_multiplier?: number;
                    };
                };
            };
            responses: {
                /** @description the swept points, ascending */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["QuantumSweep"];
                    };
                };
                /** @description no admin session */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/simulations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Runs a scenario server-side and returns metrics plus the lane-ribbon timeline (§10.1, §10.6) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        seed?: number;
                        stations?: number;
                        demand_multiplier?: number;
                        large_order_rate?: number;
                        window_from?: number;
                        window_seconds?: number;
                        /** @description A subset of UpdateSchedulerConfig::SCHEMA keys */
                        scheduler_config?: Record<string, never>;
                    };
                };
            };
            responses: {
                /** @description a day's metrics and timeline */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SimulationRun"];
                    };
                };
                /** @description no admin session — a run is unbounded compute */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/staffing_curves": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** For each open hour, the fewest stations that hold p90 under target (§10.5 #3) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        seed?: number;
                        seeds?: number;
                        demand_multiplier?: number;
                        target_seconds?: number;
                    };
                };
            };
            responses: {
                /** @description one entry per open hour, ascending */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["StaffingCurve"];
                    };
                };
                /** @description no admin session */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        MakingRow: {
            first_name: string | null;
            pickup_code: string;
            items: string[];
            eta_seconds: number;
        };
        ReadyRow: {
            first_name: string | null;
            pickup_code: string;
            ready_since_seconds: number;
            picked_up_seconds_ago: number | null;
        };
        BoardUpdate: {
            /** @enum {string} */
            type: "board_update";
            store_id: number;
            making: components["schemas"]["MakingRow"][];
            ready: components["schemas"]["ReadyRow"][];
        };
        TimelineDrink: {
            order_id: number;
            drink_id: string;
            station: number;
            started_at: number;
            finished_at: number | null;
            prep_seconds: number;
            remake: boolean;
            order_size: number;
        };
        SchedulerConfig: {
            /** @enum {string} */
            policy: "drr" | "fifo";
            quantum: number;
            aging_enabled: boolean;
            aging_rate: number;
            cohesion_enabled: boolean;
            cohesion_boost: number;
            remake_multiplier: number;
            promise_buffer: number;
            quality_limit_seconds: number;
            eta_safety_factor: number;
        };
        SchedulerConfigResponse: {
            store_id: number;
            scheduler_config: components["schemas"]["SchedulerConfig"];
            editable: string[];
        };
        SimulationMetrics: {
            orders: number;
            drinks: number;
            station_utilisation: number;
            reneged: number;
            remakes: number;
            wait_by_drink_cost: {
                cheap: {
                    orders: number;
                    p90: number;
                };
                dear: {
                    orders: number;
                    p90: number;
                };
                comparable: boolean;
                ratio: number;
            };
            eta_accuracy: {
                orders: number;
                capped: number;
                measurable: boolean;
                p50_abs: number;
                p90_abs: number;
                bias: number;
            };
            quality_breach_rate: number;
            quality_breach_rate_multi: number;
            wait_seconds: {
                p50: number;
                p90: number;
                p99: number;
            };
            by_size_class: {
                [key: string]: {
                    orders: number;
                    p90_meaningful: boolean;
                    p50: number;
                    p90: number;
                    p99: number;
                };
            };
        };
        SimulationRun: {
            seed: number;
            stations: number;
            window: {
                from: number;
                to: number;
            };
            timeline: components["schemas"]["TimelineDrink"][];
            order_spans: number[][];
            metrics: components["schemas"]["SimulationMetrics"];
        };
        KdsItem: {
            id: number;
            label: string;
            /** @enum {string} */
            status: "queued" | "in_progress" | "finished";
            prep_seconds: number;
            pickup_code: string;
            position: number;
            order_size: number;
            remake: boolean;
            quality_breach: boolean;
            station_id: number | null;
            started_at: string | null;
        };
        QueueUpdate: {
            /** @enum {string} */
            type: "queue_update";
            in_progress: components["schemas"]["KdsItem"][];
            next_up: components["schemas"]["KdsItem"][];
            depth: number;
            oldest_waiting_seconds: number;
        };
        /** @enum {string} */
        FailReason: "spill" | "wrong_order" | "quality";
        KdsSession: {
            token: string;
            expires_in: number;
            barista: {
                id: number;
                name: string;
            };
            station: {
                id: number;
                name: string;
            };
            store: {
                id: number;
                name: string;
            };
        };
        MenuOption: {
            id: number;
            name: string;
            price_cents: number;
            prep_seconds_delta: number;
        };
        OptionGroup: {
            id: number;
            name: string;
            min_select: number;
            max_select: number;
            options: components["schemas"]["MenuOption"][];
        };
        MenuItem: {
            id: number;
            name: string;
            category: string;
            price_cents: number;
            base_prep_seconds: number;
            option_groups: components["schemas"]["OptionGroup"][];
        };
        Menu: {
            items: components["schemas"]["MenuItem"][];
        };
        /** @enum {string} */
        OrderStatus: "draft" | "placed" | "in_progress" | "partially_ready" | "ready" | "picked_up" | "abandoned" | "cancelled";
        /** @enum {string} */
        DrinkStatus: "queued" | "in_progress" | "finished" | "failed" | "cancelled";
        PlacedOrderItem: {
            id: number;
            label: string;
            status: components["schemas"]["DrinkStatus"];
            prep_seconds: number;
            sequence: number;
            remake: boolean;
        };
        PlacedOrder: {
            pickup_code: string;
            status: components["schemas"]["OrderStatus"];
            /** @enum {string} */
            source: "kiosk" | "web";
            customer_first_name: string | null;
            placed_at: string;
            promised_at: string | null;
            ready_at: string | null;
            total_cents: number;
            quoted_wait_seconds: number;
            items: components["schemas"]["PlacedOrderItem"][];
        };
        OrderUpdate: {
            /** @enum {string} */
            type: "order_update";
            pickup_code: string;
            status: components["schemas"]["OrderStatus"];
            eta_seconds: number;
            items: {
                id: number;
                label: string;
                status: components["schemas"]["DrinkStatus"];
            }[];
        };
        AdminUser: {
            email: string;
        };
        Health: {
            accepting_orders: boolean;
            store_name: string;
            server_time: string;
        };
        PrepTimeStatItem: {
            menu_item_id: number;
            name: string;
            seeded_prep_seconds: number;
            ewma_seconds: number | null;
            ewma_variance: number | null;
            sample_count: number;
            confident: boolean;
            minimum_samples: number;
        };
        PrepTimeStats: {
            items: components["schemas"]["PrepTimeStatItem"][];
        };
        AblationArm: {
            id: string;
            /** @enum {string} */
            kind: "control" | "rung" | "bound";
            label: string;
            blurb: string;
            arrived: number;
            metrics: components["schemas"]["SimulationMetrics"];
        };
        Ablation: {
            seed: number;
            seeds: number;
            stations: number;
            demand_multiplier: number;
            quantum: number | null;
            arms: components["schemas"]["AblationArm"][];
        };
        QuantumSweepPoint: {
            quantum: number;
            arrived: number;
            metrics: components["schemas"]["SimulationMetrics"];
        };
        QuantumSweep: {
            seed: number;
            seeds: number;
            stations: number;
            demand_multiplier: number;
            points: components["schemas"]["QuantumSweepPoint"][];
        };
        StaffingCurveHour: {
            hour: number;
            stations: number;
            achieved: boolean;
            p90: number;
            orders: number;
            p90_meaningful: boolean;
        };
        StaffingCurve: {
            seed: number;
            seeds: number;
            demand_multiplier: number;
            target_seconds: number;
            hours: components["schemas"]["StaffingCurveHour"][];
        };
        BreakingPointPoint: {
            demand_multiplier: number;
            arrived: number;
            metrics: components["schemas"]["SimulationMetrics"];
        };
        BreakingPoint: {
            seed: number;
            seeds: number;
            stations: number;
            target_seconds: number;
            points: components["schemas"]["BreakingPointPoint"][];
            capacity: number | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
