# This file was generated by the `rails generate rspec:install` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# The generated `.rspec` file contains `--require spec_helper` which will cause
# this file to always be loaded, without a need to explicitly require it in any
# files.
#
# Given that it is always loaded, you are encouraged to keep this file as
# light-weight as possible. Requiring heavyweight dependencies from this file
# will add to the boot time of your test suite on EVERY test run, even for an
# individual file that may not need all of that loaded. Instead, consider making
# a separate helper file that requires the additional dependencies and performs
# the additional setup, and require it from the spec files that actually need
# it.
#
# Coverage gates (ADR-0002). Enforced here rather than as a separate CI step so
# there is one threshold, failing the same way locally and in CI.
#
#   COVERAGE=0 bin/rspec    disables instrumentation entirely, for spiking
#
# Loaded before anything else: SimpleCov only sees files required after it starts.
unless ENV["COVERAGE"] == "0"
  require "simplecov"

  SimpleCov.start "rails" do
    enable_coverage :branch

    skip %r{^/spec/}
    skip %r{^/config/}
    skip %r{^/db/}

    # The scheduler's own 100% line-and-branch gate does not live here any more.
    # It moved with the code into `gems/deficit_scheduler` (ADR-0033), where the
    # package *is* the strict part and SimpleCov's built-in
    # `minimum_coverage line: 100, branch: 100` enforces it directly.
    #
    # The hand-rolled `at_exit` hook that used to sit here was deleted rather
    # than repointed, on purpose. It selected files by the substring
    # `"/app/scheduler/"` and then did `unless scheduler.empty?` — so once the
    # code moved it would have matched nothing, skipped the check, and gone
    # green while enforcing nothing at all. A gate that silently stops gating is
    # worse than no gate, and its `unless empty?` was documented in a way that
    # read as intentional. ADR-0002's policy is unchanged; only its location is.
    #
    # A partial run (`bin/rspec spec/models`) can't meet a whole-project floor,
    # so only a full-suite run is gated. CI always runs the full suite.
    full_run = ARGV.none? { |a| a.start_with?("spec/") }
    minimum_coverage(line: 90) if full_run
  end
end

# See https://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
RSpec.configure do |config|
  # rspec-expectations config goes here. You can use an alternate
  # assertion/expectation library such as wrong or the stdlib/minitest
  # assertions if you prefer.
  config.expect_with :rspec do |expectations|
    # This option will default to `true` in RSpec 4. It makes the `description`
    # and `failure_message` of custom matchers include text for helper methods
    # defined using `chain`, e.g.:
    #     be_bigger_than(2).and_smaller_than(4).description
    #     # => "be bigger than 2 and smaller than 4"
    # ...rather than:
    #     # => "be bigger than 2"
    expectations.include_chain_clauses_in_custom_matcher_descriptions = true
  end

  # rspec-mocks config goes here. You can use an alternate test double
  # library (such as bogus or mocha) by changing the `mock_with` option here.
  config.mock_with :rspec do |mocks|
    # Prevents you from mocking or stubbing a method that does not exist on
    # a real object. This is generally recommended, and will default to
    # `true` in RSpec 4.
    mocks.verify_partial_doubles = true
  end

  # This option will default to `:apply_to_host_groups` in RSpec 4 (and will
  # have no way to turn it off -- the option exists only for backwards
  # compatibility in RSpec 3). It causes shared context metadata to be
  # inherited by the metadata hash of host groups and examples, rather than
  # triggering implicit auto-inclusion in groups with matching metadata.
  config.shared_context_metadata_behavior = :apply_to_host_groups

  # Two tiers for the §10.5 simulator specs (docs/testing.md, ADR-0023): CI
  # and a local `bin/rspec` run get the fast tier, every real-parameter,
  # unstubbed experiment run is tagged `:slow` and excluded unless asked for.
  #
  #   SLOW=1 bin/rspec              the full suite, including every :slow example
  #   SLOW=1 bin/rspec spec/simulator/staffing_curve_spec.rb   one file's slow examples
  #
  # This is a coverage trade, not a free lunch: `:slow` examples exist because
  # they are the ones that exercise a real parameter range end to end, so the
  # default tier does not catch a regression only visible there. Run the slow
  # tier deliberately before a release or when touching `app/simulator/**`.
  config.filter_run_excluding :slow unless ENV["SLOW"]

# The settings below are suggested to provide a good initial experience
# with RSpec, but feel free to customize to your heart's content.
=begin
  # This allows you to limit a spec run to individual examples or groups
  # you care about by tagging them with `:focus` metadata. When nothing
  # is tagged with `:focus`, all examples get run. RSpec also provides
  # aliases for `it`, `describe`, and `context` that include `:focus`
  # metadata: `fit`, `fdescribe` and `fcontext`, respectively.
  config.filter_run_when_matching :focus

  # Allows RSpec to persist some state between runs in order to support
  # the `--only-failures` and `--next-failure` CLI options. We recommend
  # you configure your source control system to ignore this file.
  config.example_status_persistence_file_path = "spec/examples.txt"

  # Limits the available syntax to the non-monkey patched syntax that is
  # recommended. For more details, see:
  # https://rspec.info/features/3-12/rspec-core/configuration/zero-monkey-patching-mode/
  config.disable_monkey_patching!

  # Many RSpec users commonly either run the entire suite or an individual
  # file, and it's useful to allow more verbose output when running an
  # individual spec file.
  if config.files_to_run.one?
    # Use the documentation formatter for detailed output,
    # unless a formatter has already been configured
    # (e.g. via a command-line flag).
    config.default_formatter = "doc"
  end

  # Print the 10 slowest examples and example groups at the
  # end of the spec run, to help surface which specs are running
  # particularly slow.
  config.profile_examples = 10

  # Run specs in random order to surface order dependencies. If you find an
  # order dependency and want to debug it, you can fix the order by providing
  # the seed, which is printed after each run.
  #     --seed 1234
  config.order = :random

  # Seed global randomization in this process using the `--seed` CLI option.
  # Setting this allows you to use `--seed` to deterministically reproduce
  # test failures related to randomization by passing the same `--seed` value
  # as the one that triggered the failure.
  Kernel.srand config.seed
=end
end
